[general]
# Redirect Streamlit’s storage to /tmp (writable in Hugging Face)
storagePath = "/tmp/.streamlit"

[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false
